### ISSUE TITLE
Consider changing Erythrite aspect's on-use effect

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [TheMysticSword/EliteVariety#15]
With Erythrites spawning only post loop, by the time you actually start fighting them and manage to roll the (default) really low chance to get the aspect, you won't get any benefit from the on-use effect since you will most likely have reached the ally cap by then, and the Imp Overlord won't spawn. A fitting alternative would be it shooting the same bleed spike volley that overlords use, maybe causing Hemorrhage instead.

**Comment by TheMysticSword** [comment]
Yep, been thinking about this too. Here are some concepts that I've come up with so far:
* Summon a Red Portal that periodically spawns regular Imps and can be killed
* Reduce the health of all impaled victims to 50%
* Teleport to the target and deal damage in a small radius after a short delay (like the Imp Overlord's teleport)
