### ISSUE TITLE
Sandstorm Elite

### ISSUE THREAD

**Issue by adelthesuper** [TheMysticSword/EliteVariety#2]
The Aoe damage is set way to high , instant killing melee characters

**Comment by TheMysticSword** [comment]
Mercenary can deal with them by using both utilities and both specials, Loader has the gauntlet punch, Acrid is a melee-range hybrid.

The sandstorm deals only 200% damage per second in a 10m radius, so the only thing that can really present a problem to melee characters with their damage are elite bosses, and by the time you meet one, you should have enough items to either survive their damage, kill them quickly or kill them off with ranged item procs. If it's not an elite teleporter boss, then you aren't even required to kill that enemy.

If I nerf the damage (which is already low), then the elite will lose its purpose - being threatening at close distance.

I think they are in a fine spot.

**Comment by adelthesuper** [comment]
On rainstorm yes that no issue but on monsoon, early game the sandstorm will instant kill whether your loader or mercenary. As soon as you touch it gg.

**Comment by adelthesuper** [comment]
thats why i recommend a config file to edit damage values.
